name: "Fist Demo Action"

on:
  push:
    branches:
      - master
jobs:
  demo-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Action is running"
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo "Hello, world!"
      - name: Run a multi-line script
        run: |
          echo "This is the first line"
          echo "This is the second line"
          echo "This is the third line"
      - name: List files
        run: ls ${{ github.workspace }}
      - name: Print GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Action completed
        run: echo "Action has completed"
