name: "Test using mocha"

on:
  push:

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: All tests passed message
        run: echo "All tests passed"
